@extends('layouts.master')

@section('title', 'News - Playstation')

@section('content')
    <h1 class="text-center py-3">News</h1>
    <p>PlayStation (Japanese: プレイステーション, Hepburn: Pureisutēshon, officially abbreviated as PS) is a video game brand that consists of five home video game consoles, two handhelds, a media center, and a smartphone, as well as an online service and multiple magazines. The brand is produced by Sony Interactive Entertainment, a division of Sony; the first PlayStation console was released in Japan in December 1994, and worldwide the following year.[1]</p>
    <p>The original console in the series was the first console of any type to ship over 100 million units, doing so in under a decade.[2] Its successor, the PlayStation 2, was released in 2000. The PlayStation 2 is the best-selling home console to date, having reached over 155 million units sold by the end of 2012.[3] Sony's next console, the PlayStation 3, was released in 2006, selling over 87.4 million units by March 2017.[4] Sony's next console, the PlayStation 4, was released in 2013, selling a million units within a day, becoming the fastest selling console in history.[5] The latest console in the series, the PlayStation 5, was released in 2020[6] and sold 10 million units in its first 249 days, unseating its predecessor as the fastest-selling PlayStation console to-date.[7]</p>
    <p>The first handheld game console in the series, the PlayStation Portable or PSP, sold a total of 80 million units worldwide by November 2013.[8] Its successor, the PlayStation Vita, which launched in Japan in December 2011 and in most other major territories in February 2012, selling over four million units by January 2013.[9] PlayStation TV is a microconsole and a non-portable variant of the PlayStation Vita handheld game console.[10] Other hardware released as part of the PlayStation series includes the PSX, a digital video recorder which was integrated with the PlayStation and PlayStation 2, though it was short-lived due to its high price and was never released outside Japan, as well as a Sony Bravia television set which has an integrated PlayStation 2. The main series of controllers utilized by the PlayStation series is the DualShock, which is a line of vibration-feedback gamepad having sold 28 million controllers by June 2008.[11]</p>
    <p>The PlayStation Network is an online service with about 110 million registered users[12] (as of June 2013) and over 103 million active users monthly.[13] (as of December 2019) It comprises an online virtual market, the PlayStation Store, which allows the purchase and download of games and various forms of multimedia, a subscription-based online service known as PlayStation Plus and a social gaming networking service called PlayStation Home, which had over 41 million users worldwide at the time of its closure in March 2015.[14] PlayStation Mobile (formerly PlayStation Suite) is a software framework that provides PlayStation content on mobile devices. Version 1.xx supports both PlayStation Vita, PlayStation TV and certain devices that run the Android operating system, whereas version 2.00 released in 2014 only targeted PlayStation Vita and PlayStation TV.[15] Content set to be released under the framework consist of only original PlayStation games currently.[16]</p>
    <p>Seventh generation PlayStation products also use the XrossMediaBar, which is an Technology & Engineering Emmy Award–winning graphical user interface.[17] A touch screen-based user interface called LiveArea was launched for the PlayStation Vita, which integrates social networking elements into the interface. Additionally, the PlayStation 2 and PlayStation 3 consoles also featured support for Linux-based operating systems; Linux for PlayStation 2 and OtherOS respectively, though this has since been discontinued. The series has also been known for its numerous marketing campaigns, the latest of which being the "Greatness Awaits" and eventually, "Play Has No Limits" commercials in the United States.
    The series also has a strong line-up of first-party games due to SIE Worldwide Studios, a group of many studios owned by Sony Interactive Entertainment that exclusively developed them for PlayStation consoles. In addition, the series features various budget re-releases of games by Sony with different names for each region; these include the Greatest Hits, Platinum, Essentials, and The Best selection of games.</p>

    <h1 class="text-center py-3">About</h1>
    <p>In 2005, Australian newspaper The Age wrote an article about the PlayStation brand. Among the numerous interviews conducted with various people in the industry was an interview with Dr Jeffrey Brand, associate professor in communication and media at Bond University who said, "PlayStation re-ignited our imagination with video games". Game designers Yoshiki Okamoto called the brand "revolutionary — PlayStation has changed gaming, distribution, sales, image and more", while Evan Wells of Naughty Dog said "PlayStation is responsible for making playing games cool."[203]</p>
    <p>In 2009, ViTrue, Inc. listed the PlayStation brand as number 13 on their "The Vitrue 100: Top Social Brands of 2009". The ranking was based on various aspects mainly dealing with popular social media sites in aspects such as Social Networking, Video Sharing, Photo Sharing and Blogs.[204]</p>
    <p>In 2010, Gizmodo stated that the PlayStation brand was one of the last Sony products to completely stand apart from its competitors, stating that "If you ask the average person on the street what their favorite Sony product is, more often than not you'll hear PlayStation".[205] As of April 2012, the PlayStation brand is the "most followed" brand on social networking site, Facebook, with over 22 million fans and followers in total which is more than any other brand in the entertainment industry. A study by Greenlight's Entertainment Retail has also shown that the PlayStation brand is the most interactive making 634 posts and tweets on social networking sites Facebook and Twitter.[206]</p>
    <p>In July 2014, Sony boasted in a company release video that the PlayStation 3, PlayStation 4 and PlayStation Vita sold a combined total of 100 million units.[207] It was announced at Tokyo Game Show on September 1, 2014, that PlayStation home game consoles claim 78% market share of all home consoles in Japan.[208]</p>
    <p>As of 2015, PlayStation is the strongest selling console brand worldwide.</p>

    <h1 class="text-center py-3">Logo Trademark</h1>
    <img src="{{ asset('images/playstation-main-logo.png') }}" alt="ps_original" width="100%" title="Original Logo">
@stop