

<?php $__env->startSection('title', 'History - Playstation'); ?>

<?php $__env->startSection('content'); ?>
    <h1 class="text-center py-3">Playstation History</h1>
    <p>PlayStation was the brainchild of Ken Kutaragi, a Sony executive who managed one of the company's hardware engineering divisions and was later dubbed "The Father of the PlayStation".</p>
    <p>Until 1991, Sony had little direct involvement with the video game industry. The company supplied components for other consoles, such as the sound chip for the Super Famicom from Nintendo, and operated a video game studio, Sony Imagesoft. As part of a joint project between Nintendo and Sony that began as early in 1988, the two companies worked to create a CD-ROM version of the Super Famicom, though Nintendo denied the existence of the Sony deal as late as March 1991. At the Consumer Electronics Show in June 1991, Sony revealed a Super Famicom with a built-in CD-ROM drive that incorporated Green Book technology or CD-i, called "Play Station" (also known as SNES-CD). However, a day after the announcement at CES, Nintendo announced that it would be breaking its partnership with Sony, opting to go with Philips instead but using the same technology. The deal was broken by Nintendo after they were unable to come to an agreement on how revenue would be split between the two companies. The breaking of the partnership infuriated Sony President Norio Ohga, who responded by appointing Kutaragi with the responsibility of developing the PlayStation project to rival Nintendo.</p>
    <img src="<?php echo e(asset('images/ps-history.jpg')); ?>" alt="ps1" width="100%" title="Playstation 1">

    <p>At that time, negotiations were still on-going between Nintendo and Sony, with Nintendo offering Sony a "non-gaming role" regarding their new partnership with Philips. This proposal was swiftly rejected by Kutaragi who was facing increasing criticism over his work with regard to entering the video game industry from within Sony. Negotiations officially ended in May 1992 and in order to decide the fate of the PlayStation project, a meeting was held in June 1992, consisting of Sony President Ohga, PlayStation Head Kutaragi and several senior members of Sony's board. At the meeting, Kutaragi unveiled a proprietary CD-ROM-based system he had been working on which involved playing video games with 3D graphics to the board. Eventually, Sony President Ohga decided to retain the project after being reminded by Kutaragi of the humiliation he suffered from Nintendo. Nevertheless, due to strong opposition from a majority present at the meeting as well as widespread internal opposition to the project by the older generation of Sony executives, Kutaragi and his team had to be shifted from Sony's headquarters to Sony Music, a completely separate financial entity owned by Sony, so as to retain the project and maintain relationships with Philips for the MMCD development project (which helped lead to the creation of the DVD).</p>
    <p>According to SCE's producer Ryoji Akagawa and chairman Shigeo Maruyama, there was uncertainty over whether the console should primarily focus on 2D sprite graphics or 3D polygon graphics. Eventually, after witnessing the success of Sega's Virtua Fighter in Japanese arcades, that Sony realized "the direction of the PlayStation became instantly clear" and 3D polygon graphics became the console's primary focus. The PlayStation logo was designed by Manabu Sakamoto. He wanted the logo to capture the 3D support of the console, but instead of just adding apparent depth to the letters "P" and "S", he created an optical illusion that suggested the letters in depth of space. Sakamoto also stuck with four bright principal colors, red, yellow, green, and blue, only having to tune the green color for better harmony across the logo. Sakamoto also designed the black and white logo based on the same design, reserved for times where colors could not be used.</p>
    <div class="text-center"><img src="<?php echo e(asset('images/ps-prototype.jpg')); ?>" alt="ps prototype" width="50%" title="Prototype of Sony Nintendo Playstation" loading="lazy"></div>

    <h1 class="text-center py-3">Formation of Sony Computer Entertainment</h1>
    <p>At Sony Music Entertainment, Kutaragi worked closely with Shigeo Maruyama, the CEO of Sony Music, and with Akira Sato to form Sony Computer Entertainment Inc. (SCEI) on November 16, 1993. A building block of SCEI was its initial partnership with Sony Music which helped SCEI attract creative talent to the company as well as assist SCEI in manufacturing, marketing and producing discs, something that Sony Music had been doing with Music Discs. The final two key members of SCEI were Terry Tokunaka, the President of SCEI from Sony's headquarters, and Olaf Olafsson. Olafsson was CEO and president of New York-based Sony Interactive Entertainment which was the parent company for the 1994-founded Sony Computer Entertainment of America (SCEA).The PlayStation project, SCEI's first official project, was finally given the green light by Sony executives in 1993 after a few years of development. Also in 1993, Phil Harrison, who later became President of SCE Worldwide Studios, was recruited into SCEI to attract developers and publishers to produce games for their new PlayStation platform.</p>
    <p>Computer Gaming World in March 1994 reported a rumor that the "Sony PS-X" would be released in Japan "before the end of this year and will retail for less than $400". After a demonstration of Sony's distribution plan as well as tech demos of its new console to game publishers and developers in a hotel in Tokyo in 1994, numerous developers began to approach PlayStation. Two of whom later became major partners were Electronic Arts in the West and Namco in Japan. One of the factors which attracted developers to the platform was the use of a 3D-capable, CD-ROM-based console which was much cheaper and easier to manufacture for in comparison to Nintendo's rival console, which used cartridge systems. The project eventually hit Japanese stores in December 1994 and gained massive sales due to its lower price point than its competitor, the Sega Saturn. The popularity of the console spread after its release worldwide in North America and Europe.</p>
    <div class="text-center"><img src="<?php echo e(asset('images/Playstation_logo_colour.png')); ?>" alt="ps logo" width="50%" title="Playstation Logo" loading="lazy"></div>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.master', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\Users\msunokas\Documents\Programavimas\Laravel\playstation\resources\views/history.blade.php ENDPATH**/ ?>